-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;
-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public."Pessoa_Id_seq";

CREATE SEQUENCE public."Pessoa_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public."Pessoa_Id_seq" OWNER TO postgres;
GRANT ALL ON SEQUENCE public."Pessoa_Id_seq" TO postgres;

-- DROP SEQUENCE public."Telefone_Id_seq";

CREATE SEQUENCE public."Telefone_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public."Telefone_Id_seq" OWNER TO postgres;
GRANT ALL ON SEQUENCE public."Telefone_Id_seq" TO postgres;

-- DROP SEQUENCE public."Usuario_Id_seq";

CREATE SEQUENCE public."Usuario_Id_seq"
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public."Usuario_Id_seq" OWNER TO postgres;
GRANT ALL ON SEQUENCE public."Usuario_Id_seq" TO postgres;
-- public."Pessoa" definition

-- Drop table

-- DROP TABLE public."Pessoa";

CREATE TABLE public."Pessoa" (
	"Id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"Nome" varchar(255) NOT NULL,
	"CPF" varchar(255) NOT NULL,
	"DataNascimento" date NOT NULL,
	"EstaAtivo" bool NOT NULL,
	CONSTRAINT "Pessoa_pkey" PRIMARY KEY ("Id")
);

-- Permissions

ALTER TABLE public."Pessoa" OWNER TO postgres;
GRANT ALL ON TABLE public."Pessoa" TO postgres;


-- public."Usuario" definition

-- Drop table

-- DROP TABLE public."Usuario";

CREATE TABLE public."Usuario" (
	"Id" serial4 NOT NULL,
	"Username" varchar(255) NOT NULL,
	"Password" varchar(255) NOT NULL,
	CONSTRAINT "Usuario_Username_key" UNIQUE ("Username"),
	CONSTRAINT "Usuario_pkey" PRIMARY KEY ("Id")
);

-- Permissions

ALTER TABLE public."Usuario" OWNER TO postgres;
GRANT ALL ON TABLE public."Usuario" TO postgres;


-- public."Telefone" definition

-- Drop table

-- DROP TABLE public."Telefone";

CREATE TABLE public."Telefone" (
	"Id" serial4 NOT NULL,
	"Numero" varchar(20) NOT NULL,
	"Tipo" varchar(20) NOT NULL,
	"IsWhatsApp" bool NOT NULL,
	"PessoaId" int4 NOT NULL,
	CONSTRAINT "Telefone_Tipo_check" CHECK ((("Tipo")::text = ANY ((ARRAY['Celular'::character varying, 'Residencial'::character varying, 'Comercial'::character varying])::text[]))),
	CONSTRAINT "Telefone_pkey" PRIMARY KEY ("Id"),
	CONSTRAINT "Telefone_PessoaId_fkey" FOREIGN KEY ("PessoaId") REFERENCES public."Pessoa"("Id") ON DELETE CASCADE
);