version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - turismo_network

  api-gateway:
    image: nginx
    container_name: gateway
    ports:
      - "80:80" # Ajuste a porta conforme necessário
    depends_on:
      - jenkins
    volumes:
      - ./gateway-api/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - turismo_network

  db-postgres:
    image: postgres
    container_name: db-postgres
    environment:
      POSTGRES_DB: db_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Ajuste a porta conforme necessário
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - turismo_network

  jenkins:
    image: jenkins/jenkins
    restart: always
    privileged: true
    user: root
    tty: true
    stdin_open: true
    ports:
      - 8090:8080
    container_name: "jenkins"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_home/jobs:/var/jenkins_home/jobs
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - turismo_network

volumes:
  jenkins_home:
  portainer_data:

networks:
  turismo_network:
    driver: bridge
